# Form implementation generated from reading ui file 'main_window_ui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1572, 1103)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"  background-color: #050313;\n"
"  color: #F3F0FC;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #050313;\n"
"  color: #F3F0FC;\n"
"}\n"
"\n"
"QFrame#splashFrame {\n"
"  background-color: #050313;\n"
"  border: 0px;\n"
"}\n"
"\n"
"QLabel#titleLabel {\n"
"  color: #5F42AB;\n"
"  font-size: 36px;\n"
"  font-weight: 700;\n"
"}\n"
"\n"
"QLabel#subtitleLabel {\n"
"  color: #A4346C;\n"
"  font-size: 18px;\n"
"}\n"
"\n"
"QLabel#hintLabel {\n"
"  color: #ACE4FC;\n"
"  font-size: 14px;\n"
"}\n"
"      ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rootLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.rootLayout.setContentsMargins(0, 0, 0, 0)
        self.rootLayout.setSpacing(0)
        self.rootLayout.setObjectName("rootLayout")
        self.splashFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.splashFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.splashFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.splashFrame.setObjectName("splashFrame")
        self.splashLayout = QtWidgets.QVBoxLayout(self.splashFrame)
        self.splashLayout.setContentsMargins(0, 0, 0, 0)
        self.splashLayout.setSpacing(0)
        self.splashLayout.setObjectName("splashLayout")
        self.splashImageLabel = QtWidgets.QLabel(parent=self.splashFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splashImageLabel.sizePolicy().hasHeightForWidth())
        self.splashImageLabel.setSizePolicy(sizePolicy)
        self.splashImageLabel.setMinimumSize(QtCore.QSize(1536, 1024))
        self.splashImageLabel.setText("")
        self.splashImageLabel.setPixmap(QtGui.QPixmap("images/splash.png"))
        self.splashImageLabel.setScaledContents(True)
        self.splashImageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.splashImageLabel.setObjectName("splashImageLabel")
        self.splashLayout.addWidget(self.splashImageLabel)
        self.rootLayout.addWidget(self.splashFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1572, 22))
        self.menubar.setVisible(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setVisible(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreferences = QtGui.QAction(parent=MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionFull_Screen = QtGui.QAction(parent=MainWindow)
        self.actionFull_Screen.setObjectName("actionFull_Screen")
        self.menuFile.addAction(self.actionFull_Screen)
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Steppy"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionFull_Screen.setText(_translate("MainWindow", "Full Screen"))
